apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo-app-deployment
  namespace: app
  labels:
    app: phpinfo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpinfo-app
  template:
    metadata:
      labels:
        app: phpinfo-app
    spec:
      containers:
        - name: phpinfo-app
          image: luannv67922/php:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo-service
  namespace: app
  labels:
    app: phpinfo-app
spec:
  selector:
    app: phpinfo-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080     # üü¢ NodePort c·ªë ƒë·ªãnh (tu·ª≥ ch·ªçn, c√≥ th·ªÉ b·ªè ƒë·ªÉ K8s t·ª± ch·ªçn)
  type: NodePort
