apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpinfo-app-deployment
  namespace: app
  labels:
    app: phpinfo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpinfo-app
  template:
    metadata:
      labels:
        app: phpinfo-app
    spec:
      containers:
        - name: phpinfo-app
          image: luannv67922/php:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: phpinfo-service
  namespace: app
  labels:
    app: phpinfo-app
spec:
  selector:
    app: phpinfo-app
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpinfo-ingress
  namespace: app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: phpinfo.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpinfo-service
                port:
                  number: 80
